; Direksiyon step motoru (23IP65-20 + DM860H) -> NUCLEO-F767ZI
;   PUL- = PE9  (CN12-52, D6)   DIR- = PE10 (CN12-47, D40)   -- ACIK DRENAJ
;   PUL+ / DIR+ = +5 V (ortak anot)          ENA = BOSTA
[env:nucleo_f767zi]
platform      = ststm32
board         = nucleo_f767zi
framework     = arduino
monitor_speed = 115200
