; Gaz — F767ZI dahili DAC (PA4 = DAC1_OUT1). Kontrolcuye BAGLI DEGILKEN olculur.
[env:nucleo_f767zi]
platform      = ststm32
board         = nucleo_f767zi
framework     = arduino
monitor_speed = 115200
